name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [blue, red, green]
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - uses: actions/checkout@v4
      - id: step1
        run: echo "test=hello${{ matrix.color }}" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world${{ matrix.color }}" >> "$GITHUB_OUTPUT"

  downstream:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: echo
        run: echo "${{ needs.build.outputs[format('output1', 'green')] }}"
